### ISSUE TITLE
Is it only basic auth? Is there a working example?

### ISSUE THREAD

**Issue by mevdev** [medianetsoftware/MNSJiraRESTClient#3]
I am trying to make a mac os x application with your library. It gives me 401s. I don't know if it is our account or the library at this point.

Do you have a simple working example of this library? Maybe you can have an 'Example' folder that utiilizes cocoapod's try functionality?

Is your library only basic auth? is there a way to change your jira settings to allow this?

Thanks

**Comment by PabloRueda** [comment]
Sorry, we don't have an Example project, however we have a test suite with the project that you can lunch to see if everything is ok.
However if the error is a 401 the most common source is that is a problem with you credentials.

**Comment by mevdev** [comment]
Thanks for the reply. My credentials work to log into Jira. 
Is the basic login the same as my user login? Do I need to have extra permissions?

**Comment by PabloRueda** [comment]
Sorry for the delay.
The basic login is the same as your user login, no extra permissions are needed.
However take into account that your user must have permission for the action you want to do (but this will be the same as if you access through the website, if you don't have permissions to create an issue in the website you will receive a 401 as well using the framework).
