### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 4ndrey** [medianetsoftware/MNSJiraRESTClient#5]
MNSGenericRestClient.h:27:2: error: unknown type name 'AFHTTPRequestOperationManager'
        AFHTTPRequestOperationManager *_manager;

**Comment by hons82** [comment]
This needs to be changed for AFNetworking 3 into [AFHTTPSessionManager](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide)

**Comment by PabloRueda** [comment]
We have just published a new version in CocoaPods (1.1.0) that fixes this problem.

Thank you.
